[project]
name = "hardware-cicd-demo"
version = "0.1.0"
description = "Hardware CI/CD Demo"
dependencies = [
    "cocotb<2.0",
    "pytest",
    "cocotb-test"
]

[tool.setuptools]
py-modules = []

[tool.pytest.ini_options]
# Only collect runner files as Pytest entrypoints
python_files = ["*_runner.py"]
